client_id: 587977431383-l2jr48fc7evicfa46oqossc8ikqa9lhk.apps.googleusercontent.com
service_email: 587977431383-l2jr48fc7evicfa46oqossc8ikqa9lhk@developer.gserviceaccount.com
key: big-query-aa83e033e5a8.p12
key_secret: notasecret
project_id: lofty-block-94022
dataset: githubarchive